apiVersion: batch/v1
kind: Job
metadata:
  name: db-initializer
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 10
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: db-init
          image: mysql:8.0
          command: [ "/bin/bash", "-c" ]
          args:
            - |
              echo "Waiting for MySQL to become ready..."
              # Aumentiamo la resilienza del check
              until mysql -h mysql -u root -p$MYSQL_ROOT_PASSWORD -e "SELECT 1"; do
                echo "MySQL is not yet available, retrying in 5s..."
                sleep 5
              done
              
              echo "MySQL is ready. Creating databases..."
              mysql -h mysql -u root -p$MYSQL_ROOT_PASSWORD <<EOF
              CREATE DATABASE IF NOT EXISTS inventory;
              CREATE DATABASE IF NOT EXISTS orders;
              CREATE DATABASE IF NOT EXISTS user;
              GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';
              FLUSH PRIVILEGES;
              EOF
              
              echo "âœ… Database initialization completed."
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: yamar-secrets
                  key: mysql-root-password