apiVersion: v1
kind: ConfigMap
metadata:
  name: product-config
  labels:
    app: product-service
data:
  # -----------------------------------------------------------------------
  # MongoDB Connection Parameters
  # -----------------------------------------------------------------------
  SPRING_DATA_MONGODB_HOST: "mongodb" # Matches Helm Release name
  SPRING_DATA_MONGODB_PORT: "27017"
  SPRING_DATA_MONGODB_DATABASE: "product"
  SPRING_DATA_MONGODB_USERNAME: "derain"

  # Identity Provider
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "http://keycloak:8080/realms/derain-yamar"