apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:

      initContainers:
        - name: wait-for-mongodb
          image: busybox:latest
          command:
            - 'sh'
            - '-c'
            - |
              echo "Waiting for MongoDB..."
              # Nota: la porta di Mongo nel service Ã¨ 27017
              until nc -z mongodb 27017; do 
                echo "waiting for mongodb:27017..."
                sleep 2
              done
              echo "MongoDB is up!"

      containers:
        - name: product-service
          image: yamar-product-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8041
          envFrom:
            - configMapRef:
                name: product-config
          env:
            # -----------------------------------------------------------------
            # SECURITY INJECTION
            # Password is retrieved from the Kubernetes Secret 'yamar-secrets'
            # -----------------------------------------------------------------
            - name: SPRING_DATA_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: yamar-secrets
                  key: mongodb-passwords
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /api/v1/actuator/health/liveness
              port: 8041
            initialDelaySeconds: 180
            periodSeconds: 20
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /api/v1/actuator/health/readiness
              port: 8041
            initialDelaySeconds: 120
            periodSeconds: 20
            failureThreshold: 10