spring:
  data:
    mongodb:
      host: localhost
      port: 27020

  elasticsearch:
    uris: http://localhost:9200

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      properties:
        schema.registry.url: http://localhost:8084