spring:
  data:
    mongodb:
      uri: mongodb://derain:derain@localhost:27020/product?authSource=admin

  elasticsearch:
    uris: http://localhost:9200

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      properties:
        schema.registry.url: http://localhost:8084
        value.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicRecordNameStrategy
    consumer:
      properties:
        schema.registry.url: http://localhost:8084
        value.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicRecordNameStrategy

  config:
    import: "optional:file:services/env.properties"