apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "yamar-service.fullname" . }}
  labels:
    {{- include "yamar-service.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: "default"

  {{- range .Values.env }}
  {{ .name }}: {{ .value | quote }}
  {{- end }}
