apiVersion: v1
kind: Service
metadata:
  name: {{ include "yamar-service.fullname" . }}
  labels:
    {{- include "yamar-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "yamar-service.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: http
