apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-config
  labels:
    app: inventory-service
data:
  SPRING_PROFILES_ACTIVE: "default"
  # -----------------------------------------------------------------------
  # MySQL Connection Parameters
  # Note: Uses the same host as Order Service, but 'inventory' database.
  # -----------------------------------------------------------------------
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/inventory?allowPublicKeyRetrieval=true&useSSL=false"
  SPRING_DATASOURCE_USERNAME: "root"