apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  labels:
    app: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:

      initContainers:
        - name: wait-for-mysql
          image: busybox:latest
          command:
            - 'sh'
            - '-c'
            - |
              echo "Waiting for MySQL..."
              until nc -z mysql 3306; do 
                echo "waiting for mysql:3306..."
                sleep 2
              done
              echo "MySQL is up!"

      containers:
        - name: inventory-service
          image: yamar-inventory-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8043
          envFrom:
            - configMapRef:
                name: inventory-config
          env:
            # -----------------------------------------------------------------
            # SECURITY INJECTION
            # -----------------------------------------------------------------
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: yamar-secrets
                  key: mysql-root-password
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /api/v1/actuator/health/liveness
              port: 8043
            initialDelaySeconds: 180
            periodSeconds: 20
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /api/v1/actuator/health/readiness
              port: 8043
            initialDelaySeconds: 120
            periodSeconds: 20
            failureThreshold: 10