filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      templates:
        - condition:
            contains:
              docker.container.image: "yamar-"
          config:
            - type: container
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log
              json.keys_under_root: true
              json.add_error_key: true
              json.message_key: message

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "yamar-%{[service.name]:other}-%{+yyyy.MM.dd}"

setup.template.name: "yamar"
setup.template.pattern: "yamar-*"
setup.ilm.enabled: false