apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:

      initContainers:
        - name: wait-for-mysql
          image: busybox:latest
          command:
            - 'sh'
            - '-c'
            - |
              echo "Waiting for MySQL..."
              until nc -z mysql 3306; do 
                echo "waiting for mysql:3306..."
                sleep 2
              done
              echo "MySQL is up!"

      containers:
        - name: order-service
          image: yamar-order-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8042
          envFrom:
            - configMapRef:
                name: order-config
          env:
            # -----------------------------------------------------------------
            # SECURITY INJECTION
            # Root password for MySQL retrieved from Secrets
            # -----------------------------------------------------------------
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: yamar-secrets
                  key: mysql-root-password
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI
              valueFrom:
                secretKeyRef:
                  name: yamar-secrets
                  key: auth0-issuer-uri
          resources:
            requests:
              memory: "300Mi"
              cpu: "150m"
            limits:
              memory: "600Mi"
          livenessProbe:
            httpGet:
              path: /api/v1/actuator/health/liveness
              port: 8042
            initialDelaySeconds: 180
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /api/v1/actuator/health/readiness
              port: 8042
            initialDelaySeconds: 120
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 10