spring:
  datasource:
    url: jdbc:mysql://localhost:3312/orders
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      properties:
        schema.registry.url: http://localhost:8084

  config:
    import: "optional:file:services/env.properties"

application:
  config:
    product-service:
      url: http://localhost:8041/api/v1/products
    inventory-service:
      url: http://localhost:8043/api/v1/inventory
    user-service:
      url: http://localhost:8044/api/v1/users