spring:
  datasource:
    url: jdbc:mysql://localhost:3312/orders
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      properties:
        schema.registry.url: http://localhost:8084
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://YOUR_AUTH0_DOMAIN/

application:
  config:
    inventory-service:
      url: http://localhost:8043/api/v1/inventory
    product-service:
      url: http://localhost:8041/api/v1/products