downstream-services:
  product-service:
    url: http://localhost:8041
  order-service:
    url: http://localhost:8042
  inventory-service:
    url: http://localhost:8043
  user-service:
    url: http://localhost:8044

logging:
  level:
    com.yamar.gatewayservice: DEBUG

spring:
  config:
    import: "optional:file:services/env.properties"

management:
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 10s