downstream-services:
  product-service:
    url: http://localhost:8041
  order-service:
    url: http://localhost:8042
  inventory-service:
    url: http://localhost:8043

logging:
  level:
    com.yamar.gatewayservice: DEBUG

spring:
  config:
    import: "optional:file:services/env.properties"