spring:
  application:
    name: gateway-service

server:
  port: 8222

application:
  config:
    services:
      product:
        url: http://localhost:8041
        path: /api/v1/products/**
      order:
        url: http://localhost:8042
        path: /api/v1/orders/**
      inventory:
        url: http://localhost:8043
        path: /api/v1/inventory/**