spring:
  application:
    name: gateway-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9099/realms/derain-yamar

server:
  port: 8222

application:
  config:
    services:
      product:
        url: http://localhost:8041
        path: /api/v1/products/**
      order:
        url: http://localhost:8042
        path: /api/v1/orders/**
      inventory:
        url: http://localhost:8043
        path: /api/v1/inventory/**