server:
  port: ${GATEWAY_PORT:9090}

spring:
  application:
    name: gateway-service
  profiles:
    active: dev

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service
              uri: ${downstream-services.product-service.url}
              predicates:
                - Path=${api-config.base-path}/products/**
            - id: order-service
              uri: ${downstream-services.order-service.url}
              predicates:
                - Path=${api-config.base-path}/orders/**
            - id: inventory-service
              uri: ${downstream-services.inventory-service.url}
              predicates:
                - Path=${api-config.base-path}/inventory/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.issuer-uri}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
  api-docs:
    path: /v3/api-docs
