api-config:
  base-path: /api/v1
  server-description: API Gateway Development

api-docs-discovery:
  services:
    - name: Product Service
      url: ${api-config.base-path}/api-docs
      serviceUrl: ${downstream-services.product-service.url}
      contextPath: ${api-config.base-path}
    - name: Order Service
      url: ${api-config.base-path}/api-docs
      serviceUrl: ${downstream-services.order-service.url}
      contextPath: ${api-config.base-path}
    - name: Inventory Service
      url: ${api-config.base-path}/api-docs
      serviceUrl: ${downstream-services.inventory-service.url}
      contextPath: ${api-config.base-path}

downstream-services:
  product-service:
    url: http://localhost:8041
  order-service:
    url: http://localhost:8042
  inventory-service:
    url: http://localhost:8043

logging:
  level:
    com.yamar.gatewayservice: DEBUG
